### ISSUE TITLE
Binary Registry bug within PSDesiredStateConfiguration "Registry" Resource

### ISSUE THREAD

**Issue by JakeDean3631** [Microsoft/PowerStigDsc#14]
**Describe the bug**
Attempting to set a binary registry key to 0 will result in the key being set to "zero-length binary value" due to a bug with the registry resource parsing the value of 0 into a binary format. 

**To Reproduce**
1. Create a test configuration containing the following: 

Configuration TestConfig {

     Import-DSCResource -ModuleName 'PSDesiredStateConfiguration'
     
     Nodename $Nodename 
     {
           Registry 'Registry(INF): HKLM:\System\CurrentControlSet\Control\Lsa\FullPrivilegeAuditing'
          {
	       ValueName = 'FullPrivilegeAuditing'
	       ValueType = 'Binary'
	       Key = 'HKLM:\System\CurrentControlSet\Control\Lsa'
               ValueData = 0
               Ensure = "Present"
               Force = $True
            }
     }
}

2. Generate a MOF and push the configuration. 
3. Check the HKLM:\System\CurrentControlSet\Control\Lsa registry key, it will be set to "Zero-Length Binary Value." 
4. Set the valuedata to 1, and it will parse correctly, resulting in the key being set to "01"
5. Regardless of how you attempt to set the "00" value, it will result in the "Zero-Length Binary Value

 **Expected behavior**
HKLM:\System\CurrentControlSet\Control\Lsa registry key should be set to "00"

**Screenshots**
![image](https://user-images.githubusercontent.com/35388475/43272997-53304066-90c9-11e8-853e-002bb9b27d45.png)

![image](https://user-images.githubusercontent.com/35388475/43273013-5d15e658-90c9-11e8-8ca7-08a8b8afc23f.png)

**Additional context**
Work-around is importing the xPSDesiredStateConfiguration module and using the xRegistry resource, which will parse the value of "0" into a binary key of "00" 

Example:

Configuration TestConfig {

     Import-DSCResource -ModuleName 'xPSDesiredStateConfiguration'
     
     Nodename $Nodename 
     {
           xRegistry 'Registry(INF): HKLM:\System\CurrentControlSet\Control\Lsa\FullPrivilegeAuditing'
          {
	       ValueName = 'FullPrivilegeAuditing'
	       ValueType = 'Binary'
	       Key = 'HKLM:\System\CurrentControlSet\Control\Lsa'
               ValueData = 0
               Ensure = "Present"
               Force = $True
            }
     }
}

Link to the original bug: https://github.com/PowerShell/DscResources/issues/203

**Comment by athaynes** [comment]
@JakeDean3631 Do you want to take a stab at submitting the change so you get credit on the contributor's list?

**Comment by athaynes** [comment]
This issue was moved to Microsoft/PowerStig#70
