### ISSUE TITLE
SqlServer README and Examples update

### ISSUE THREAD

**Issue by chasewilson** [Microsoft/PowerStigDsc#15]
**Is your feature request related to a problem? Please describe.**
Sql Server Composite Stig README is not in compliance with the project format and there are no SQL Server Examples

**Describe the solution you'd like**
Remove SqlServer README and update Project README. Add SqlServer examples to Project

**Describe alternatives you've considered**

**Additional context**

**Comment by athaynes** [comment]
This issue was moved to Microsoft/PowerStig#69
